name: bentopdf

services:
  bentopdf:
    image: bentopdf/bentopdf-simple:latest
    restart: unless-stopped
    networks:
      - tailscale
    labels:
      tsdproxy.enable: true
      tsdproxy.name: pdf

networks:
  tailscale:
    external: true
