name: bentopdf

services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:latest
    restart: unless-stopped
    networks:
      - tailscale
    labels:
      tsbridge.enable: true
      tsbridge.service.name: pdf

networks:
  tailscale:
    external: true
