name: bentopdf

services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:latest
    restart: unless-stopped
    labels:
      docktail.service.enable: true
      docktail.service.name: pdf
      docktail.service.port: 8080
      docktail.service.service-port: 443
