name: cloudflared

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file: cloudflared.secret
    # TUNNEL_TOKEN
    networks:
      - cloudflared

networks:
  cloudflared:
    name: cloudflared
