name: comet

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: comet
      POSTGRES_PASSWORD: comet
      POSTGRES_DB: comet
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - tailscale

  comet:
    image: g0ldyy/comet
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DASHBOARD_ADMIN_PASSWORD: comet
      DATABASE_TYPE: postgresql
      DATABASE_URL: comet:comet@postgres:5432
      SCRAPE_COMET: true
      SCRAPE_ZILEAN: true
      SCRAPE_TORRENTIO: true
      SCRAPE_MEDIAFUSION: true
    env_file:
      - comet.secret
    volumes:
      - data:/app/data
    networks:
      - tailscale
    labels:
      tsdproxy.enable: true
      tsdproxy.name: comet
      tsdproxy.container_port: 8000

volumes:
  data:
  postgres:

networks:
  tailscale:
    external: true
