# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:

[global]
  z             # enable zeroconf
  e2dsa         # enable file indexing and filesystem scanning
  e2ts          # enable multimedia indexing
  e2vu          # patches the database with the new hashes from the filesystem
  ansi          # enable colors in log messages (both in logfiles and stdout)
  dedup         # enable file deduplication
  no-robots     # disalllow robots
  force-js      # disables the plain HTML folder listing
  rproxy: 1     # allow 1 hop forwarding forwarding
  xff-src: lan  # allow forwarding from lan
  xff-hdr: cf-connecting-ip   # get real ip from cloudflared
  vc-url: https://api.copyparty.eu/advisories
  vc-age: 3     # how many hours to wait between each check
  vc-exit       # emergency-exit if current version is vulnerable
  ah-alg: argon2    # hash paswords
  ah-salt: random-string-for-my-argon   # hashing salt
  shr: /w       # allow sharable links
  name: copyparty

[accounts]
  boran: +MdNBI1BqLi7A2Ef9r9oSTnfvpjMpg08T

[/]
  /w
  accs:
    g: *
    A: boran
