# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:

[global]
  z             # enable zeroconf
  e2dsa         # enable file indexing and filesystem scanning
  e2ts          # enable multimedia indexing
  ansi          # enable colors in log messages (both in logfiles and stdout)
  dedup         # enable file deduplication
  no-robots     # disalllow robots
  force-js
  rproxy: 1     # allow 1 hop forwarding forwarding
  xff-src: lan  # allow forwarding from lan
  xff-hdr: cf-connecting-ip
  vc-url: https://api.copyparty.eu/advisories
  vc-age: 3     # how many hours to wait between each check
  vc-exit       # emergency-exit if current version is vulnerable
  ah-alg: argon2
  ah-salt: random-string-for-my-argon

[accounts]
  boran: +MdNBI1BqLi7A2Ef9r9oSTnfvpjMpg08T

[/]
  /w
  accs:
    A: boran

# [/paperless]
#   /w/paperless
#   accs:
#     A: boran
#
# [/dump]
#   /w/dump
#   accs:
#     wG: *
#     A: boran
#   flags:
#     e2d, d2t, fk: 4
