name: forgejo

services:
  server:
    image: codeberg.org/forgejo/forgejo:15
    restart: unless-stopped
    env_file: forgejo.secret
    # FORGEJO__database__NAME
    # FORGEJO__database__USER
    # FORGEJO__database__PASSWD
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO____APP_NAME=Forgejo
      - FORGEJO____APP_SLOGAN=
      - FORGEJO____APP_DISPLAY_NAME_FORMAT={APP_NAME}
      - FORGEJO__server__DOMAIN=git.boranseckin.com
      - FORGEJO__server__ROOT_URL=https://git.boranseckin.com
      - FORGEJO__server__SSH_DOMAIN=mossy.dorper-lake.ts.net:222
      - FORGEJO__server__LANDING_PAGE=/boranseckin
      - FORGEJO__ui_0x2E_meta__AUTHOR=Boran Seckin
      - FORGEJO__ui_0x2E_meta__DESCRIPTION=A personal Git server hosting open-source projects and experiments. Browse repositories, track issues, and explore code.
      - FORGEJO__ui_0x2E_meta__KEYWORDS=git,open-source,code,repositories,forge,forgejo
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '222:22'
    networks:
      - forgejo
      - cloudflared
    depends_on:
      - db

  db:
    image: postgres:17
    restart: unless-stopped
    env_file: forgejo.secret
    # POSTGRES_USER
    # POSTGRES_PASSWORD
    # POSTGRES_DB
    networks:
      - forgejo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  data:
  pgdata:

networks:
  forgejo:
    name: forgejo
  cloudflared:
    external: true
