name: obsidian

services:
  couchdb:
    image: couchdb:latest
    restart: unless-stopped
    env_file: obsidian.secret
    # COUCHDB_USER
    # COUCHDB_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    volumes:
      - data:/opt/couchdb/data
      - etc:/opt/couchdb/etc/local.d
    labels:
      docktail.service.enable: true
      docktail.service.name: obsidian
      docktail.service.port: 5984
      docktail.service.service-port: 443

volumes:
  data:
  etc:
