name: obsidian

services:
  couchdb:
    image: couchdb:latest
    restart: unless-stopped
    environment:
      - COUCHDB_USER=obsidian
      - COUCHDB_PASSWORD=obsidian
    volumes:
      - /share/obsidian/data:/opt/couchdb/data
      - /share/obsidian/etc:/opt/couchdb/etc/local.d
    networks:
      - tailscale
    labels:
      tsdproxy.enable: true
      tsdproxy.name: obsidian
      tsdproxy.container_port: 5984

networks:
  tailscale:
    external: true
