name: obsidian

services:
  couchdb:
    image: couchdb:latest
    restart: unless-stopped
    user: 5984:5984
    environment:
      - COUCHDB_USER=obsidian
      - COUCHDB_PASSWORD=obsidian
    volumes:
      - /share/obsidian/data:/opt/couchdb/data
      - /share/obsidian/etc:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
    networks:
      - tailscale
    labels:
      tsdproxy.enable: true
      tsdproxy.name: obsidian

networks:
  tailscale:
    external: true
