name: obsidian

services:
  couchdb:
    image: couchdb:latest
    restart: unless-stopped
    env_file: obsidian.secret
    # COUCHDB_USER
    # COUCHDB_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    volumes:
      - data:/opt/couchdb/data
      - etc:/opt/couchdb/etc/local.d
    networks:
      - tailscale
    labels:
      tsdproxy.enable: true
      tsdproxy.name: obsidian
      tsdproxy.container_port: 5984

volumes:
  data:
  etc:

networks:
  tailscale:
    external: true
