services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    restart: unless-stopped
    volumes:
      - data:/data
      - ./:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tailscale
    ports:
      - "8080:8080"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

volumes:
  data:

networks:
  tailscale:
    driver: bridge
    name: tailscale
