name: tailscale

services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    restart: unless-stopped
    volumes:
      - data:/data
      - ./:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tailscale
    ports:
      - "8888:8888"

volumes:
  data:

networks:
  tailscale:
    driver: bridge
    name: tailscale
