name: tailscale

services:
  docktail:
    image: ghcr.io/marvinvr/docktail:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/tailscale:/var/run/tailscale
    environment:
      LOG_LEVEL: warn
    env_file: tailscale.secret
    # TAILSCALE_OAUTH_CLIENT_ID
    # TAILSCALE_OAUTH_CLIENT_SECRET
