name: vert

services:
  vert:
    image: ghcr.io/vert-sh/vert:latest
    restart: unless-stopped
    networks:
      - tailscale
    labels:
      tsbridge.enable: true
      tsbridge.service.name: convert

networks:
  tailscale:
    external: true
