name: vert

services:
  vert:
    image: ghcr.io/vert-sh/vert:latest
    restart: unless-stopped
    labels:
      docktail.service.enable: true
      docktail.service.name: convert
      docktail.service.port: 80
      docktail.service.service-port: 443
