
name: vert

services:
  vert:
    image: ghcr.io/vert-sh/vert:latest
    restart: unless-stopped
    networks:
      - tailscale
    labels:
      tsdproxy.enable: true
      tsdproxy.name: convert

networks:
  tailscale:
    external: true
