name: viniplay

services:
  viniplay:
    image: ardovini/viniplay
    restart: unless-stopped
    volumes:
      - viniplay:/data
    env_file: viniplay.secret
    # SESSION_SECRET
    labels:
      docktail.service.enable: true
      docktail.service.name: tv
      docktail.service.port: 8998
      docktail.service.service-port: 443

volumes:
  viniplay:
